### ISSUE TITLE
License

### ISSUE THREAD

**Issue by richardjgowers** [andrewtarzia/mol-ellipsize#2]
Hi @andrewtarzia You've reused a GPL piece of code (the ellipse fitter) then licensed this package as MIT - the licenses are not compatible this way round.  You should look up license compatibility yourself, but you'll either need to relicense this package as GPL or reimplement the ellipse fitter.

**Comment by andrewtarzia** [comment]
@richardjgowers thank you for the heads up! Did this ages ago before I understood. Will fix asap!

**Comment by andrewtarzia** [comment]
This has been completed and updated on pypi with version 1.0.2.

Thank you again @richardjgowers
